### PR TITLE
Fix duplicate css and js resource entries in final HTML when a fragment is included more than once

### LINKED ISSUE #83: When including a fragment multiple times, resources of that fragment (JS, CSS) are repeated in the final HTML.
$subject.

### PR DESCRIPTION
**Pull request by callkalpa**
In `CssHelper` and `HeadJsHelper`, a HashSet in `com.github.jknack.handlebars.Options.data` is used to store the resolved placeholders. So a css or js resource placeholder will be resolved only if it is not resolved already. Hence we can avoid duplication of css and/or js resource entry in the final HTML even the same fragment (from which the css and js resources come from) is included more than once.

Resolves #83

### CODE REVIEW

File: components/uuf-renderablecreator-hbs/src/main/java/org/wso2/carbon/uuf/renderablecreator/hbs/helpers/runtime/CssHelper.java [hunk 1]
```diff
@@ -48,8 +50,14 @@ public CharSequence apply(String relativePath, Options options) throws IOExcepti
...
+        String content = buffer.toString();
 
-        addToPlaceholder(buffer.toString(), options);
+        if (isPlacedholderResolved(content, options)) {
+            return "";
+        }
+
+        addToPlaceholder(content, options);
+        ((HashSet<String>) options.data(RESOLVED_PLACEHOLDERS)).add(content);
         return "";
```
Comment (imesh) [inline components/uuf-renderablecreator-hbs/src/main/java/org/wso2/carbon/uuf/renderablecreator/hbs/helpers/runtime/CssHelper.java]: It seems like this method is always returning a blank string. If so is there any reason to make the return type string/char sequence?
