### PR TITLE
Fixing internationalization not working properly in Safari browser

### LINKED ISSUE #154: Internationalization doesn't work in Safari browser
The values we have set from `en_US.properties` file in `lang` folder, does not get picked-up when webapp is accessed through the Safari browser.

Please refer _[UUF] User Portal's Localization properties are not working in Safari browser_ mail thread at at DEV mailing list

### PR DESCRIPTION
**Pull request by Shan1024**
Fixes #154 

This PR will fix the issue of internationalization not working properly on some browsers. The locale to be used for each request is calculated when the helper is called for the first time and then it is stored in the i18n helper's **options** for the later use. This is done to improve performance.

Also this PR also renames the `{{t}}` helper to `{{i18n}}`.

### CODE REVIEW

File: components/uuf-core/src/main/java/org/wso2/carbon/uuf/api/config/I18nResources.java [hunk 1]
```diff
@@ -30,7 +30,7 @@
  */
 public class I18nResources {
 
-    private final Map<String, Properties> i18nResources = new HashMap<>();
+    private final SortedMap<String, Properties> i18nResources = new TreeMap<>();
```
Comment (Kishanthan) [inline components/uuf-core/src/main/java/org/wso2/carbon/uuf/api/config/I18nResources.java]: why the map types have been changed?

Comment (Shan1024) [inline components/uuf-core/src/main/java/org/wso2/carbon/uuf/api/config/I18nResources.java]: This is done to increase the performance. Keys in the tree maps will be sorted. So when we compare strings to get the i18n resource for a language (using startsWith in https://github.com/wso2/carbon-uuf/pull/159/files#diff-3aeccabd74d63e95c4ffca677a908412R58), we gain some performance improvement because we compare less elements.

As an example lets say we have following locales.
* en
* en-uk
* en-us

When we get **en** in the request, it matches with the **en** in the above list in the first try. So even though we use `startsWith` method, we get the **en** file because it is in the beginning of the list. If we get **en-uk**, it will be matched with the second element in the list.

But if we use a **HashMap**, the **key set** is not sorted, so we cannot say when it will be matched and we cannot sort the **keyset** for every request.

File: components/uuf-renderablecreator-hbs/src/main/java/org/wso2/carbon/uuf/renderablecreator/hbs/helpers/runtime/I18nHelper.java [hunk 2]
```diff
@@ -27,10 +27,11 @@
 
 public class I18nHelper implements Helper<String> {
 
-    public static final String HELPER_NAME = "t";
-    private static final String DEFAULT_LOCALE = "en_US";
+    public static final String HELPER_NAME = "i18n";
+    private static final String DEFAULT_LOCALE = "en-us";
     private static final String LOCALE_HEADER = "Accept-Language";
     private static final String LOCALE = "locale";
+    private static final String CURRENT_LOCALE = "CURRENT_LOCALE";
```
Comment (this) [inline components/uuf-renderablecreator-hbs/src/main/java/org/wso2/carbon/uuf/renderablecreator/hbs/helpers/runtime/I18nHelper.java]: Add prefix `DATA_KEY_` to this constant.

File: components/uuf-renderablecreator-hbs/src/main/java/org/wso2/carbon/uuf/renderablecreator/hbs/helpers/runtime/I18nHelper.java [hunk 3]
```diff
@@ -27,10 +27,11 @@
 
 public class I18nHelper implements Helper<String> {
 
-    public static final String HELPER_NAME = "t";
-    private static final String DEFAULT_LOCALE = "en_US";
+    public static final String HELPER_NAME = "i18n";
+    private static final String DEFAULT_LOCALE = "en-us";
     private static final String LOCALE_HEADER = "Accept-Language";
     private static final String LOCALE = "locale";
```
Comment (this) [inline components/uuf-renderablecreator-hbs/src/main/java/org/wso2/carbon/uuf/renderablecreator/hbs/helpers/runtime/I18nHelper.java]: Since this constant is used only once, shall we remove it and inline the value?
